### ISSUE TITLE
Parser Structure

### ISSUE THREAD

**Issue by stursberg** [HPI-BP2017N2/Parser-deprecated-#5]
Parser is a microservice that get input data (HTML file + root URL of shop as String) and put output data (the Offer JSON).

Parser searches data in HTML file in specials places, which defined with selectors in rulesJSON's. There are 3 such files: Schema, JsonLd and ShopRules.

* Schema and JsonLd are static JSON files with rules set with selectors for every relevant attribute. The Parser just extract data that contains in matching selectors on HTML page and write it in offer JSON.

* ShopRules sends "root url" of the shop to RulesRepo (https://github.com/tomschw/ShopRulesGenerator/issues/1) and get response with the ShopRules JSON. Then it extract data that contains in matching selectors on HTML page and write it in offer JSON.

The Offer JSON contains data, getting from all rules sets (Schema, JsonLd and ShopRules), even if it's duplicated.

**Comment by deeps96** [comment]
- [x] extract productAttributes using given rules
- [x] extract attributes using jsonld and schema.org
- [ ] extract attributes using shoprules
- [x] save extracted product attributes into file using spring repository as storage provider

**Comment by deeps96** [comment]
This user story has a dependency on tomschw/ShopRulesGenerator#1
